<?php
// $Id$

/**
 * @file
 * Enables HTTP Auth security or an HTML form to restrict site access.
 */

/**
 * Secure Site status: Disabled
 */
define('SECURESITE_DISABLED', 0);

/**
 * Secure Site status: Always on
 */
define('SECURESITE_ALWAYS', 1);

/**
 * Secure Site status: Only when site is offline
 */
define('SECURESITE_OFFLINE', 2);

/**
 * Secure Site status: Only for restricted pages
 */
define('SECURESITE_403', 3);

/**
 * Secure Site type: Web browser HTTP Auth security
 */
define('SECURESITE_BASIC', 0);

/**
 * Secure Site type: HTTP digest
 */
define('SECURESITE_DIGEST', 1);

/**
 * Secure Site type: HTML log-in form
 */
define('SECURESITE_FORM', 2);

/**
 * Implementation of hook_help().
 */
function securesite_help($path, $arg) {
  switch ($path) {
    case 'admin/help#securesite':
      module_load_include('inc', 'securesite', 'securesite.admin');
      return _securesite_admin_help();
  }
}

/**
 * Implementation of hook_perm().
 */
function securesite_perm() {
  return array('access secured pages');
}

/**
 * Implementation of hook_menu().
 */
function securesite_menu() {
  $items['securesite_403'] = array(
    'page callback' => '_securesite_403',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'securesite.inc',
  );
  $items['admin/settings/securesite'] = array(
    'title' => 'Secure Site',
    'description' => 'Enables HTTP Auth security or an HTML form to restrict site access.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('securesite_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'securesite.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_form_$form-id_alter().
 */
function securesite_form_system_error_reporting_settings_alter(&$form, &$form_state) {
  if (variable_get('securesite_enabled', SECURESITE_403)) {
    $form['securesite_403'] = $form['site_403'];
    $form['securesite_403']['#default_value'] = variable_get('securesite_403', '');
    unset($form['site_403']);
  }
}

/**
 * Implementation of hook_boot().
 */
function securesite_boot() {
  global $user, $base_path;
  switch (variable_get('securesite_type', SECURESITE_BASIC)) {
    case SECURESITE_BASIC:
      // PHP in CGI mode work-arounds. Sometimes "REDIRECT_" prefixes $_SERVER variables. See http://www.php.net/reserved.variables.
      if (empty($_SERVER['HTTP_AUTHORIZATION']) && !empty($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])) {
        $_SERVER['HTTP_AUTHORIZATION'] = $_SERVER['REDIRECT_HTTP_AUTHORIZATION'];
      }
      if (!empty($_SERVER['HTTP_AUTHORIZATION'])) {
        list($_SERVER['PHP_AUTH_USER'], $_SERVER['PHP_AUTH_PW']) = explode(':', base64_decode(substr($_SERVER['HTTP_AUTHORIZATION'], 6)));
      }
      // Check for credentials in HTTP headers.
      if (isset($_SERVER['PHP_AUTH_USER'])) {
        $edit['name'] = $_SERVER['PHP_AUTH_USER'];
      }
      if (isset($_SERVER['PHP_AUTH_PW'])) {
        $edit['pass'] = $_SERVER['PHP_AUTH_PW'];
      }
      // If credentials are present, log in.
      if (!empty($edit)) {
        // Fix missing indexes.
        $edit += array('name' => '', 'pass' => '');
        // If this is a new user, perform log-in.
        if ($edit['name'] !== $user->name && $edit['name'] !== $_SESSION['securesite_guest']) {
          drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);
          module_load_include('inc', 'securesite');
          _securesite_basic_auth($edit);
        }
      }
      // If credentials are missing, request them.
      else {
        // Don't request credentials if user is logged in or if running from command line or cron.
        if (empty($user->uid) && empty($_SESSION['securesite_guest']) && php_sapi_name() != 'cli' && request_uri() != $base_path .'cron.php') {
          drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);
          module_load_include('inc', 'securesite');
          _securesite_dialog();
        }
      }
      break;
    case SECURESITE_DIGEST:
      // Check for credentials in HTTP headers.
      $parts = explode(',', trim($_SERVER['PHP_AUTH_DIGEST']));
      $edit = array();
      foreach ($parts as $part) {
        if (!empty($part)) {
          list($key, $value) = explode('=', trim($part), 2);
          $key = $key == 'username' ? 'name' : $key;
          $edit[$key] = trim($value, '"');
        }
      }
      // If credentials are present, log in.
      if (array_diff(array('cnonce', 'name', 'nc', 'nonce', 'qop', 'response', 'uri'), array_keys($edit)) == array()) {
        // If this is a new user, perform log-in.
        if ($edit['name'] !== $user->name && $edit['name'] !== $_SESSION['securesite_guest']) {
          drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);
          module_load_include('inc', 'securesite');
          _securesite_digest_auth($edit);
        }
        break;
      }
      // If credentials are missing, check for Post credentials.
    case SECURESITE_FORM:
      // Check for credentials in Post data. If credentials are present, log in.
      if (isset($_POST['securesite_login_form']) && !empty($_POST['edit'])) {
        // Fix missing indexes.
        $edit = $_POST['edit'] + array('name' => '', 'pass' => '');
        drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);
        module_load_include('inc', 'securesite');
        _securesite_basic_auth($edit);
      }
      // If credentials are missing, request them.
      else {
        // Don't request credentials if user is logged in or if running from command line or cron.
        if (empty($user->uid) && empty($_SESSION['securesite_guest']) && php_sapi_name() != 'cli' && request_uri() != $base_path .'cron.php') {
          drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);
          module_load_include('inc', 'securesite');
          _securesite_dialog();
        }
      }
      break;
  }
}

/**
 * Implementation of hook_user().
 *
 * When users logout, show the HTTP Auth dialog to make sure the HTTP Auth
 * credentials are cleared
 */
function securesite_user($op, &$edit, &$user) {
  switch ($op) {
    case 'insert':
    case 'load':
      if (variable_get('securesite_type', SECURESITE_BASIC) == SECURESITE_DIGEST && isset($edit['pass'])) {
        if (db_result(db_query_range("SELECT uid FROM {securesite} WHERE uid = %d", $user->uid, 0, 1)) === FALSE) {
          db_query("INSERT INTO {securesite} (uid, pass) VALUES (%d, '%s')", $user->uid, $edit['pass']);
        }
      }
      break;
    case 'after_update':
      if (variable_get('securesite_type', SECURESITE_BASIC) == SECURESITE_DIGEST && isset($edit['pass'])) {
        if (db_result(db_query_range("SELECT uid FROM {securesite} WHERE uid = %d", $user->uid, 0, 1)) === FALSE) {
          db_query("UPDATE {securesite} SET pass = '%s' WHERE uid = %d", $edit['pass'], $user->uid);
        }
        else {
          securesite_user('insert', $edit, $user);
        }
      }
      break;
    case 'delete':
      db_query("DELETE FROM {securesite} WHERE uid = %d", $user->uid);
      break;
    case 'logout':
      $securesite_type = variable_get('securesite_type', SECURESITE_BASIC);
      if (($securesite_type == SECURESITE_BASIC || $securesite_type == SECURESITE_DIGEST) && !empty($_SESSION['securesite_login'])) {
        module_load_include('inc', 'securesite');
        // Load the anonymous user
        $user = drupal_anonymous_user();
        // Clear stored credentials
        _securesite_dialog();
      }
      break;
  }
}

