<?php

function securesite_perm() {
  return array('access site');
}

function securesite_help($section) {
  if ($section == 'admin/modules#description') {
    return t('Lets you use basic HTTP authentication for log in.');
  }
}

function securesite_init() {
  global $user, $base_url;

  $guest_name = variable_get('securesite_guest_name', '');
  $guest_pass = variable_get('securesite_guest_pass', '');
  $edit = array('name'=> $_SERVER['PHP_AUTH_USER'], 'pass' => $_SERVER['PHP_AUTH_PW']);
  if (!module_hook('user', 'authenticate')) {
    drupal_load('module', 'user');
  }
  if (!securesite_page_match() || ($user->uid && user_access('access site')) || (!empty($guest_name) && $guest_name == $edit['name'] && $guest_pass == $edit['pass'])) {
    return;
  }

  if (!empty($_POST)) {
    securesite_user_pass();
  }

  if (($account = user_authenticate($edit['name'], $edit['pass'])) && user_access('access site', $account)) {
    $user = $account;
    watchdog('user', securesite_t('Session opened for %name.', array('%name' => securesite_theme_placeholder($user->name))));
    user_login_submit('user_login', $edit);
    $_SESSION['securesite_auth'] = TRUE;
  }
  else {
    _securitesite_auth();
    exit;
  }
}
function securesite_page_match($refresh = false) {
  static $page_match = null;

  if (is_null($page_match) || $refresh) {
    $pages = variable_get('securesite_pages', FALSE);
    if ($pages) {
      $path = drupal_get_path_alias($_GET['q']);
      $regexp = '/^('. preg_replace(array('/(\r\n?|\n)/', '/\\\\\*/', '/(^|\|)\\\\<front\\\\>($|\|)/'), array('|', '.*', '\1'. preg_quote(variable_get('site_frontpage', 'node'), '/') .'\2'), preg_quote($pages, '/')) .')$/';
      $page_match = preg_match($regexp, $path);
    }
    else {
      $page_match = variable_get('securesite_enabled', 0);
    }
  }
  return $page_match;
}

function securesite_user($op, &$edit, &$user) {
  if ($op == 'logout' && $_SESSION['securesite_auth']) {
    unset($_SESSION['securesite_auth']);
    _securitesite_auth();
    unset($user);
    module_invoke_all('exit', request_uri());
    exit;
  }
}

function _securitesite_auth() {
  header('WWW-Authenticate: Basic realm="'. str_replace("\n", ' ', (variable_get('site_name', 'local'))) .'"');
  header('HTTP/1.0 401 Unauthorized');
  securesite_user_pass();
}


function securesite_goto() {
  global $base_url;
  $url = (arg(0) == 'logout' ? $base_url :  request_uri());
  if (ini_get('session.use_trans_sid') && session_id() && !strstr($url, session_id())) {
    $url .= (strstr($url, '?') && !strstr($url, $sid) ? '&' : '?'). session_name() .'='. session_id();
  }
  module_invoke_all('exit', $url);
  header('Location: '. $url);
}

function securesite_t($string, $args = 0) {
  if (!$args) {
    return $string;
  }
  else {
    return strtr($string, $args);
  }
}

function securesite_theme_placeholder($text) {
  return '<strong>'. htmlspecialchars($text, ENT_QUOTES) .'</strong>';
}

function securesite_settings() {
  include('securesite.inc');
  return _securesite_settings();
}

function securesite_user_pass() {
  include('securesite.inc');
  _securesite_user_pass();
}
