securesite.settings:
    type: mapping
    label: 'Securesite settings'
    mapping:
      securesite_enabled:
        type: integer
        label: 'Securesite Enabled'
      securesite_type:
        type: sequence
        sequence:
          - type: integer
            label: 'Securesite Type'
      securesite_guest_name:
        type: string
        label: 'Guest Name'
      securesite_guest_pass:
        type: string
        label: 'Guest Password'
      securesite_login_form:
        type: string
        label: 'Login Form Message'
        translatable: true
      securesite_reset_form:
        type: string
        label: 'Password Reset Form Message'
        translatable: true
      securesite_digest_script:
        type: string
        label: 'Location of Digest Script'
      securesite_password_script:
        type: string
        label: 'Location of Password Script'
      securesite_realm:
        type: string
        label: 'Digest Authentication Realm'
      securesite_403:
        type: string
        label: 'Access Denied Page'



